"""create initial

Revision ID: 11717889bb78
Revises: 
Create Date: 2026-02-12 16:59:23.902780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11717889bb78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player1', sa.Integer(), nullable=False),
    sa.Column('player2', sa.Integer(), nullable=False),
    sa.Column('board', sa.JSON(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.CheckConstraint('player1 != player2', name='check_players_different'),
    sa.ForeignKeyConstraint(['current_turn'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player1'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_player1'), 'games', ['player1'], unique=False)
    op.create_index(op.f('ix_games_player2'), 'games', ['player2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_player2'), table_name='games')
    op.drop_index(op.f('ix_games_player1'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
