"""add status in table games

Revision ID: 99943975a87b
Revises: f766c18ebd79
Create Date: 2026-02-12 19:13:45.706378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99943975a87b'
down_revision: Union[str, Sequence[str], None] = 'f766c18ebd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
